app/Festival.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Festival extends Model
{

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = ['id', 'name', 'location', 'geo_lat', 'geo_long', 'headliners', 'start_date', 'end_date', 'size', 'cost', 'info', 'why_to_go', 'website', 'other_artists'];
    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [];


    public function review()
    {
        return $this->hasMany('App\Review');
    }

    public function planned()
    {
        //ToDo: fix it!
        //return $this->hasMany('App\Planner', 'planned_festivals');
    }

    public function attended()
    {
        //ToDo: fix it!
        //return $this->hasMany('App\Planner', 'attended_festivals');
    }

    public function showArtists()
    {
        $artists = json_decode($this->other_artists);

        if (is_array(json_decode($this->other_artists))) {
            $artists = implode(', ', json_decode($this->other_artists));
        }

        return $artists;
    }

    public function scopeName($query, $name)
    {
        if ($name) {
            $query = $query->where('name', 'like', '%' . $name . '%');
        }

        return $query;
    }

    public function scopeHeadliners($query, $headliners)
    {
        if ($headliners) {
            $query = $query->where('headliners', 'like', '%' . $headliners . '%');
        }

        return $query;
    }

    public function scopeDate($query, $date)
    {
        if ($date) {
            //ToDo: need fix it!
            $query = $query->where('start_date', $date);
        }

        return $query;
    }

    public function scopePrice($query, $from, $to)
    {
        if ($from) {
            $query = $query->where('cost', '>=', $from);
        }

        if ($to) {
            $query = $query->where('cost', '<=', $to);
        }

        return $query;
    }


}

app/Http/Controllers/Admin/FestivalController.php
<?php namespace App\Http\Controllers\Admin;

use App\Festival;
use App\Http\Controllers\AdminController;
use App\Http\Requests\Admin\DeleteRequest;
use Datatables;


class FestivalController extends AdminController
{

    /*
    * Display a listing of the resource.
    *
    * @return Response
    */
    public function index()
    {
        // Show the page
        return view('admin.festivals.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function getCreate()
    {
        return view('admin.festivals.create_edit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function postCreate(UserRequest $request)
    {

        $festival = new Festival ();
        $festival->name = $request->name;
        $festival->city = $request->city;
        $festival->country = $request->country;
        $festival->street = $request->street;
        $festival->postalcode = $request->postalcode;
        $festival->geo_lat = $request->geo_lat;
        $festival->geo_long = $request->geo_long;
        $festival->headliners = $request->headliners;
        $festival->start_date = $request->start_date;
        $festival->end_date = $request->end_date;
        $festival->size = $request->size;
        $festival->cost = $request->cost;
        $festival->info = $request->info;
        $festival->why_to_go = $request->why_to_go;
        $festival->website = $request->website;
        $festival->other_artists = $request->other_artists;
        $festival->start_date = date($request->password);
        $festival->end_date = date($request->password);
        $festival->confirmed = $request->confirmed;
        $festival->save();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param $user
     * @return Response
     */
    public function getEdit($id)
    {

        $festival = Festival::find($id);
        return view('admin.festivals.create_edit', compact('festival'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param $user
     * @return Response
     */
    public function postEdit(UserEditRequest $request, $id)
    {

        $festival = Festival::find($id);
        $festival->name = $request->name;
        $festival->confirmed = $request->confirmed;

        $password = $request->password;
        $passwordConfirmation = $request->password_confirmation;

        if (!empty($password)) {
            if ($password === $passwordConfirmation) {
                $user->password = bcrypt($password);
            }
        }
        $user->save();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param $user
     * @return Response
     */

    public function getDelete($id)
    {
        $festival = Festival::find($id);
        // Show the page
        return view('admin.festivals.delete', compact('festival'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param $user
     * @return Response
     */
    public function postDelete(DeleteRequest $request, $id)
    {
        $festival = Festival::find($id);
        $festival->delete();
    }

    /**
     * Show a list of all the languages posts formatted for Datatables.
     *
     * @return Datatables JSON
     */
    public function data()
    {
        $festivals = Festival::select(array('festivals.id', 'festivals.name', 'festivals.country', 'festivals.headliners', 'festivals.start_date', 'festivals.end_date'));

        return Datatables::of($festivals)
            // ->edit_column('confirmed')
            ->add_column('actions', '@if ($id!="1")<a href="{{{ URL::to(\'admin/festivals/\' . $id . \'/edit\' ) }}}" class="btn btn-success btn-sm iframe" ><span class="glyphicon glyphicon-pencil"></span>  {{ trans("admin/modal.edit") }}</a>
                    <a href="{{{ URL::to(\'admin/festivals/\' . $id . \'/delete\' ) }}}" class="btn btn-sm btn-danger iframe"><span class="glyphicon glyphicon-trash"></span> {{ trans("admin/modal.delete") }}</a>
                @endif')
            ->remove_column('id')
            ->make();
    }

}

app/Http/Controllers/FestivalController.php
<?php

namespace App\Http\Controllers;

use App\Festival;
use App\Http\Requests;
use App\Repositories\Festival\FestivalRepository;
use App\Repositories\User\UserRepository;
use Auth;

class FestivalController extends Controller
{
    private $user;
    private $festival;

    /**
     * FestivalController constructor.
     * @param UserRepository $user
     */
    public function __construct(UserRepository $user, FestivalRepository $festival)
    {
        $this->user = $user;
        $this->festival = $festival;
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function index($id = null)
    {
        $activeFestival = null;
        if ($id) {
            $activeFestival = $this->festival->find($id);
        }
        $festivals = Festival::all();

        return view('festivals.index')
            ->with(compact('festivals', 'activeFestival'));

    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return Response
     */
    public function show($id)
    {
        $festival = Festival::findOrFail($id);
        $festivalPlan = null;

        if (Auth::check()) {
            $festivalPlan = [
                'plan' => Auth::user()->planner()->where('festival_id', $festival->id)->first(),
                'attender' => Auth::user()->attenders()->where('festival_id', $festival->id)->first(),
                'want' => Auth::user()->wants()->where('festival_id', $festival->id)->first()
            ];
        }

        return view('festivals.show')
            ->with('festival', $festival)
            ->with('plan', $festivalPlan);
    }
}

resources/views/festivals/index.blade.php
@extends('app')

@section('styles')
    <link rel="stylesheet" href="/css/common.css">
    <link rel="stylesheet" href="/css/festival-list.css">
@stop

@section('content')

    <div class="page-header">
        <div class="container">
            <div class="row">
                <div class="col-md-3 center-align user-mini-dash">
                    @include('includes.profile')
                </div>
                <div class="col-md-9">
                    @if($activeFestival)
                        @include('festivals.short', ['festival' => $activeFestival, 'onlyInfo' => false])
                    @endif
                </div>
            </div>
            <!-- end row -->
        </div>
        <!-- end container -->
    </div> <!-- end page-header -->
    <div class="container-fluid map">
        <div class="container">
            @foreach($festivals->chunk(3) as $festivalSet)
                <div class="row">
                    @foreach($festivalSet as $festival)
                        <div class="col-md-4 festival-block {{ $activeFestival && $activeFestival->id == $festival->id ? 'festival-active' : null}}">
                            <a href="{{ route('festival.preview', $festival->id) }}"><span>{{ $festival->name }}</span></a>
                        </div>
                    @endforeach
                </div>
            @endforeach
        </div>
    </div>
@stop

@section('scripts')
    <script>
        $('.festival-block').on('click', function () {
            window.location = $(this).find('a').attr('href');
        });
    </script>
@stop

resources/views/festivals/short.blade.php
@section('styles')
    @parent

    <link rel="stylesheet" href="/css/common.css">
    <link rel="stylesheet" href="/css/festival-list.css">
@stop

@section('scripts')
    @parent

    <script src="/js/festival/short.js"></script>
@stop

<div class="row">
    <div class="pre-header">
        <div>
            @if(! $onlyInfo)
                <div class="col-md-6">
                    <div class="float-right">
                        @if(! (Auth::user()->planner()->where('festival_id', $festival->id)->first()))
                            <form method="post" action="{{ route('festival.add-to-plan', $festival->id) }}">
                                {{ csrf_field()  }}
                                <button class="btn btn-default">Add to plan</button>
                            </form>
                        @else
                            <form method="post" action="{{ route('festival.remove-from-plan', $festival->id) }}">
                                {{ csrf_field()  }}
                                <button class="btn btn-default">Remove from plan</button>
                            </form>
                        @endif
                    </div>
                </div>
                <div class="col-md-6">
                    <a href="{{ route('reviews.create', $festival->id) }}" class="btn btn-default">Review</a>
                    <a href="{{ route('festivals') }}" class="btn btn-danger float-right">Close</a>
                </div>
            @endif
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6 festival-info">
        <div class="festival-short-info">
            <p><span class="label-normal indent-right"><b>{{ $festival->name }}</b></span></p>

            <p><span class="label-normal indent-right"><b>Headliners:</b></span>{{ $festival->headliners }}</p>

            <p><span class="label-normal indent-right"><b>Dates:</b></span>
                {{ $festival->start_date . ($festival->end_date ? ( ' - ' . $festival->end_date) : '') }}</p>

            @if($festival->cost)
                <p><span class="label-normal indent-right"><b>Cost:</b></span>{{ $festival->cost }}</p>
            @endif
        </div>
    </div>
    <div class="col-md-6">
        <div class="festival-short-info">
            <p>{!! nl2br($festival->info) !!}</p>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-md-6 text-align-center">
        Player
    </div>
    <div class="col-md-6 text-align-center">
        <a class="btn btn-primary" href="{{ route('festival', $festival->id) }}">View Full
            Info</a>
    </div>
</div>

resources/views/festivals/show.blade.php
@extends('app')

@section('styles')
    <link rel="stylesheet" href="/css/common.css">
    <link rel="stylesheet" href="/components/slick-carousel/slick/slick-theme.css">
    <link rel="stylesheet" href="/components/slick-carousel/slick/slick.css">
@stop

@section('scripts')
    <script src="/js/festival/show.js"></script>
    <script src="/components/slick-carousel/slick/slick.min.js"></script>
    <script>
        $(function () {
            $('#carousel').slick();
        });
    </script>
@stop

@section('content')
    <div class="container">
        <div class="row festival-subheader">
            <div class="col-md-4">
                <h4 class="header">{{ $festival->name }}</h4>
            </div>


            <div class="col-md-2 sm">
                <div class="header-button">
                    @if($plan['plan'])
                        <form method="POST"
                              action="{{ URL::route('festival.remove-from-plan', ['id' => $festival->id]) }}"
                              id="form-remove-from-plan">
                            {{ csrf_field() }}
                            <p>
                                <a id="remove-from-plan">Remove<br> from plan</a>
                            </p>
                        </form>
                    @else
                        <form method="POST" action="{{ URL::route('festival.add-to-plan', ['id' => $festival->id]) }}"
                              id="form-add-to-plan">
                            {{ csrf_field() }}
                            <p>
                                <a id="add-to-plan">Add<br> to plan</a>
                            </p>
                        </form>
                    @endif
                </div>
            </div>


            <div class="col-md-2 sm">
                <div class="header-button">
                    @if($plan['attender'])
                        <form method="POST"
                              action="{{ URL::route('festival.remove-been-here', ['id' => $festival->id]) }}"
                              id="form-remove-i-been-here">
                            {{ csrf_field() }}
                            <p>
                                <a id="remove-i-been-here">I not have<br> been here</a>
                            </p>
                        </form>
                    @else
                        <form method="POST"
                              action="{{ URL::route('festival.add-been-here', ['id' => $festival->id]) }}"
                              id="form-add-i-been-here">
                            {{ csrf_field() }}
                            <p>
                                <a id="add-i-been-here">I've<br> been here</a>
                            </p>
                        </form>
                    @endif
                </div>
            </div>

            <div class="col-md-2 sm">
                <div class="header-button">
                    @if($plan['want'])
                        <form method="POST"
                              action="{{ URL::route('festival.remove-from-want-list', ['id' => $festival->id]) }}"
                              id="form-remove-from-want-list">
                            {{ csrf_field() }}
                            <p>
                                <a id="remove-from-want-list">I not<br> want to go</a>
                            </p>
                        </form>
                    @else
                        <form method="POST"
                              action="{{ URL::route('festival.add-to-want-list', ['id' => $festival->id]) }}"
                              id="form-add-to-want-list">
                            {{ csrf_field() }}
                            <p>
                                <a id="add-to-want-list">I<br> want to go</a>
                            </p>
                        </form>
                    @endif
                </div>
            </div>

            <div class="col-md-2 sm">
                <div class="header-button">
                    <p><a href="{{ route('reviews.create', $festival->id) }}">Review/<br>Submit Photos</a></p>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        <div class="row">
            <div class="page-header height-400">
                <div class="row">
                    <div class="col-md-12 head-title">
                        {{ $festival->name }}
                    </div>
                </div>
            </div>
            <!-- end row -->
        </div>
        <!-- end container -->
    </div> <!-- end page-header -->

    <div class="container">
        <div class="row">
            <div class="col-md-12" data-slick='{"slidesToShow": 4, "slidesToScroll": 4}' id="carousel">
                <div class="img-carousel"><img src="/img/submit-photos.png" alt=""></div>
                <div class="img-carousel"><img src="/img/submit-photos.png" alt=""></div>
                <div class="img-carousel"><img src="/img/submit-photos.png" alt=""></div>
                <div class="img-carousel"><img src="/img/submit-photos.png" alt=""></div>
                <div class="img-carousel"><img src="/img/submit-photos.png" alt=""></div>
                <div class="img-carousel"><img src="/img/submit-photos.png" alt=""></div>
            </div>
            <div class="col-md-8">
                <article>
                    <div class="body">
                        <p><b>Headliner:</b> {{ $festival->headliners }}</p>

                        <p><b>Dates:</b> {{ $festival->start_date }}{{ $festival->end_date }}</p>

                        <p><b>Accomodation:</b> {{ $festival->accomodation }}</p>

                        <p><b>Why to go:</b> {{ $festival->why_to_go }}</p>

                        <p><b>Official website:</b> <a href="{{ $festival->website }}">{{ $festival->website }}</a></p>

                        <p><b>Top tips:</b></p>

                        <p><b>Other artists:</b> {{ $festival->showArtists() }} </p>

                        <p><b>Info:</b> {{ $festival->info }}</p>
                    </div>
                    <div class="col-md-2">
                    </div>
                </article>
            </div>
        </div>
    </div>
@stop